### ISSUE TITLE
¿Por qué no reconoce el comando rollup -c?

### ISSUE THREAD

**Issue by angeldiaz017** [BIMrras/Curso-IFC.js#3]
Buenos días,
Estoy intentando hacer un **bundle** (siguiendo el ejercicio 2 de la segunda clase). He instalado la librería web-ifc y también rollup (con el comando _npm install --save-dev rollup @rollup/plugin-node-resolve_ ) He copiado el archivo de configuración. Cuando ejecuto **rollup -c** me salta el siguiente error:
[image](https://user-images.githubusercontent.com/86513910/152154380-283799ec-e63c-4939-8634-1be15a357aa4.png)
Me da la sensación de que no detecta que está instalada la librería o de que el terminal no está apuntando en la dirección correcta, pero no consigo corregir el error. Muchas gracias :)

**EDIT**
La ejecución de rollup -c parece que apunta al directorio correcto, que es donde está _index.js_ ([image](https://user-images.githubusercontent.com/86513910/152157814-9acca54b-9f78-4cac-89fe-55a5ff7ec95a.png))
Además, parece que está bien instalada porque aparece dentro de _node_modules_ y dentro de _package.json_. Así que no sé muy bien por donde puede venir el error

**Comment by angeldiaz017** [comment]
**EDIT**
He encontrado una solución, ejecuta el _bundle_ si pongo en la línea de comandos npx rollup -c (en vez de poner rollup -c) :D

**Comment by agviegas** [comment]
Genial! Alternativamente puedes probar a instalar rollup de forma global con `npm i rollup -g`.

**Comment by angeldiaz017** [comment]
Sí, lo vi en el curso. Pero me daba problemas porque la ejecución de scripts está deshabilitada en el sistema. Entonces no estaba seguro de modificar los permisos :/. Muchas gracias @agviegas !
