### ISSUE TITLE
¿cómo  puedo acceder a constantes que se declaran dentro de una función declarada en un evento?

### ISSUE THREAD

**Issue by angeldiaz017** [BIMrras/Curso-IFC.js#5]
Buenas tardes,
Tengo una duda muy concreta (que puede ser que sea más de js que de ifc.js. Si es así dímelo y consulto por otras vías :D) Escribo el código y te comento:
```js
button.onchange=async(event) =>{
  const file=event.target.files[0]
  const url=URL.createObjectURL(FILE
  const ifcModel=await.viewer.IFC.loadIfcUrl(url,true)
}
```
Lo que busco es poder acceder a ifcModel desde fuera de la función que se activa cuando se carga un fichero en el elemento html que representa **button**.  Algo similar a:
```js
const n1=2
const n2=3
const a=sum(n1,n2)

function sum(n1,n2){
     return const result=n1+n2
}
```
En este caso, a es accesible desde fuera de la función pero IfcModel no (he probado con el return y guardar en una variable pero guarda el atributo onchage del objeto html)
Muchísimas muchísimas gracias :D

**Comment by agviegas** [comment]
Algo así?

```js
const models = [];
button.onchange=async(event) =>{
  const file=event.target.files[0]
  const url=URL.createObjectURL(FILE
  const ifcModel=await.viewer.IFC.loadIfcUrl(url,true)
  models.push(ifcModel);
}
console.log(models[0]);
```

**Comment by angeldiaz017** [comment]
Justo, perfecto gracias ;D
